[WIP] Update of the inertial parameters #100
Ipuch/bioNC pull request #105
Opened 2023-10-31 12:28 UTC by ANaaim

* [X] Linked issue related to your pull request using '#XXX' 
* [X] Used the tag [WIP] or [RTR] for on-going changes, or for ready to review
* [ ] Did you write new tests to cover your changes?
* [ ] Did you write a proper documentation (docstrings and ReadMe)
* [X] Please black your code `black . -l120`

2023-10-31 18:51 UTC, Ipuch requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/105)* status: all files reviewed, 1 unresolved discussion (waiting on @ANaaim)

___
*[`bionc/model_creation/biomechanical_model_template.py` line 129 at r1](https://reviewable.io/reviews/Ipuch/bioNC/105#-Ni62wWo1vMNYKMY5NB2:-Ni62wWo1vMNYKMY5NB3:b-sbxfp4) ([raw file](https://github.com/Ipuch/bioNC/blob/5dd827fc34c5a05cba9c6e9836252b87e68425ef/bionc/model_creation/biomechanical_model_template.py#L129)):*
> ```Python
>                     inertia_matrix=s.inertia_parameters.inertia,
>                     transformation_matrix=TransformationMatrixType.Buv,
>                 )
> ```

Okay, does this works for you ? here are my toughts:

The user should only be considered by the choice of Inertia Parameters Antropometric Table Item such as Dumas2007.Thigh for example.
thus, at that stage we need to be able to pass the length computed just before ("v = rp -rd") to compute the inertia parameters from the identified length.

What do you think ? 

Also, if we uncomment this feature, we need to test to maintain it :+1: 



_Code quote:_
```Python
                natural_segment.set_inertial_parameters(
                    mass=s.inertia_parameters.relative_mass,
                    center_of_mass=s.inertia_parameters.center_of_mass,
                    inertia_matrix=s.inertia_parameters.inertia,
                    transformation_matrix=TransformationMatrixType.Buv,
                )
```


<!-- Sent from Reviewable.io -->

2023-11-07 17:30 UTC, Ipuch requested changes
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/105)* status: all files reviewed, 1 unresolved discussion (waiting on @ANaaim)

___
*[`bionc/model_creation/biomechanical_model_template.py` line 129 at r1](https://reviewable.io/reviews/Ipuch/bioNC/105#-Ni62wWo1vMNYKMY5NB2:-NieomFzDEqC8rURtjno:b-4ngyje) ([raw file](https://github.com/Ipuch/bioNC/blob/5dd827fc34c5a05cba9c6e9836252b87e68425ef/bionc/model_creation/biomechanical_model_template.py#L129)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Okay, does this works for you ? here are my toughts:

The user should only be considered by the choice of Inertia Parameters Antropometric Table Item such as Dumas2007.Thigh for example.
thus, at that stage we need to be able to pass the length computed just before ("v = rp -rd") to compute the inertia parameters from the identified length.

What do you think ? 

Also, if we uncomment this feature, we need to test to maintain it :+1:
</blockquote></details>


model["THIGH"].set_inertia_paramters(
mass=
center_of_mass_inertia=
inertia=
)

def set\_inertial\_parameters(  
    self,  
    mass: float,  
    center\_of\_mass: np.ndarray,  
    inertia\_matrix: np.ndarray,  
    transformation\_matrix: TransformationMatrixType,  
):  
    self.\_natural\_inertial\_parameters = NaturalInertialParameters.from\_cartesian\_inertial\_parameters(  
        mass\=mass,  
        center\_of\_mass\=center\_of\_mass,  
        inertia\_matrix\=inertia\_matrix,  
        inertial\_transformation\_matrix\=self.compute\_transformation\_matrix(transformation\_matrix),  
    )  
    self.\_mass = mass  
    self.\_natural\_center\_of\_mass = self.\_natural\_inertial\_parameters.natural\_center\_of\_mass  
    self.\_natural\_pseudo\_inertia = self.natural\_pseudo\_inertia  
    self.\_mass\_matrix = self.\_natural\_inertial\_parameters.mass\_matrix


<!-- Sent from Reviewable.io -->

2023-11-07 17:32 UTC, ANaaim commented
Do not forget to use 
_update_mass_matrix from bionc/biomechanical model after seting inertia

2024-01-12 08:32 UTC, ANaaim commented
Should i still work on this ?

2024-01-12 14:31 UTC, Ipuch commented
I think this PR should be closed as this is not the spirit of the model creation to allow passing numerical values. But mostly to pass the numerical values after the "kinematic model only was updated", like I said in my last comment.


```python3
model["THIGH"].set_inertia_paramters(
mass=1,
center_of_mass_inertia=[1,2,3],
inertia=[1,2,3,4,5,6],
)

def set_inertial_parameters(
self,
mass: float,
center_of_mass: np.ndarray,
inertia_matrix: np.ndarray,
transformation_matrix: TransformationMatrixType,
):
self._natural_inertial_parameters = NaturalInertialParameters.from_cartesian_inertial_parameters(
mass=mass,
center_of_mass=center_of_mass,
inertia_matrix=inertia_matrix,
inertial_transformation_matrix=self.compute_transformation_matrix(transformation_matrix),
)
self._mass = mass
self._natural_center_of_mass = self._natural_inertial_parameters.natural_center_of_mass
self._natural_pseudo_inertia = self.natural_pseudo_inertia
self._mass_matrix = self._natural_inertial_parameters.mass_matrix
```

I don't remember if I implemented it. 
If yes, this PR should be closed, if No, you could revert some commit of this PR and start from here or open a new one.

2025-02-11 20:22 UTC, Ipuch commented
Close as outdated

2025-02-11 20:22 UTC, closed without merging