[RTR] new initialization methods Issue #101
Ipuch/bioNC pull request #132
Opened 2024-01-11 12:25 UTC by aaiaueil

* [ ] Linked issue related to your pull request using '#XXX' 
* [ ] Used the tag [WIP] or [RTR] for on-going changes, or for ready to review
* [ ] Did you write new tests to cover your changes?
* [ ] Did you write a proper documentation (docstrings and ReadMe)
* [ ] Please black your code `black . -l120`

2024-01-12 20:30 UTC, Ipuch requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/132)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @aaiaueil)

___
*[`bionc/bionc_numpy/initial_guess_mode_type.py` line 8 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzI_Ph-FgXrzqEXFZs:-NnzI_Pi-HptVH75mX4-:b-8oj1ik) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/initial_guess_mode_type.py#L8)):*
> ```Python
>     USER_PROVIDED = ("UserProvided",)
>     USER_PROVIDED_FIRST_FRAME_ONLY = ("UserProvidedFirstFrameOnly",)
>     FROM_FIRST_FRAME_MARKERS = "FromFirstFrameMarkers"
> ```

Put this in enums.py
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 72 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzIeFmDSjdUzqKs3H-:-NnzIeFmDSjdUzqKs3H0:b9azwlt) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/inverse_kinematics.py#L72)):*
> ```Python
>         self,
>         model: BiomechanicalModel,
>         initial_guess_mode: Enum,
> ```

What you wrote is not wrong but this would be more precise.
```python3
initial_guess_mode: InitialGuessModeType,
```
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 74 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzJ82r36n-9kqV4bVV:-NnzJ82sDZVSKegVTIQR:b-xlsklr) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/inverse_kinematics.py#L74)):*
> ```Python
>         initial_guess_mode: Enum,
>         Q_init: np.ndarray | NaturalCoordinates = None,
>         initialize_markers: np.ndarray = None,
> ```

I believe this new entry is a mistake, this is a mistake to remove !!



_Code quote:_
```Python
        initialize_markers: np.ndarray = None,
```
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 132 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzJfAOBwkWM07cMU2P:-NnzJfAOBwkWM07cMU2Q:b-2d4qrw) ([raw file](https://github.com/Ipuch/bioNC/blob/c8f5efb3c4742e2649473d5dbc53e643d36ab53d/bionc/bionc_numpy/inverse_kinematics.py#L132)):*
> ```Python
>                 raise NotImplementedError("Not available yet, please provide Q_init")
>             else:
>                 self.Q_init = self.model.Q_from_markers(self.experimental_markers[:, :, :])
> ```

You deleted this line that is absolutely major !!
It computes the Q from markers, and it can be used without providing 'initialize_markers'
in the case of "FROM_MARKERS", this function needs to be used.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 253 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzKF_c-ninaEiVH_le:-NnzKF_c-ninaEiVH_lf:b-iu8vze) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/inverse_kinematics.py#L253)):*
> ```Python
>             self.initialize_markers = initialize_markers
> 
>         self.initial_guess_mode = initial_guess_mode
> ```

Please displace this section of code in the method `solve`.
and encapsulate it in a method name  ̀get_Q_init_from_initial_guess_mode(...) `



_Code quote:_
```Python
        if initial_guess_mode == InitialGuessModeType.USER_PROVIDED:
            if Q_init is None:
                raise ValueError("Please provide Q_init if you want to use USER_PROVIDED mode")
            if Q_init.shape[1] != self.nb_frames:
                raise ValueError("Please make sure Q_init contains all the frames")
            self.Q_init = Q_init

        elif initial_guess_mode == InitialGuessModeType.USER_PROVIDED_FIRST_FRAME_ONLY:
            if Q_init is None:
                raise ValueError("Please provide Q_init if you want to use USER_PROVIDED_FIRST_FRAME_ONLY mode")
            if len(Q_init.shape) > 1:
                raise ValueError("Please provide only the first frame for Q_init")
            if self._frame_per_frame == False:
                raise ValueError("Please set frame_per_frame to True")
            self.Q_init = Q_init

        elif initial_guess_mode == InitialGuessModeType.FROM_CURRENT_MARKERS:
            if initialize_markers is None:
                raise ValueError("Please provide initialize_markers in order to initialize the optimization")
            if initialize_markers.shape[2] != self.nb_frames:
                raise ValueError("Please make sure initalize_markers contains all the frames")
            if experimental_heatmaps is not None:
                raise ValueError(
                    "Q_init cannot be computed from markers using heatmap data, please either provide marker data or change initialization mode"
                )
            self.initialize_markers = initialize_markers

        elif initial_guess_mode == InitialGuessModeType.FROM_FIRST_FRAME_MARKERS:
            if initialize_markers is None:
                raise ValueError("Please provide initialize_markers in order to initialize the optimization")
            if len(initialize_markers.shape) > 2:
                raise ValueError("Please provide only the first frame for markers")
            if experimental_heatmaps is not None:
                raise ValueError(
                    "Q_init cannot be computed from markers using heatmap data, please either provide marker data or change initialization mode"
                )
            if self._frame_per_frame == False:
                raise ValueError("Please set frame_per_frame to True")
            self.initialize_markers = initialize_markers

        self.initial_guess_mode = initial_guess_mode
```
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 317 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzKdbf8diHHy01QplI:-NnzKdbf8diHHy01QplJ:b-k97mye) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/inverse_kinematics.py#L317)):*
> ```Python
>     def solve(
>         self, method: str = "ipopt", options: dict = None
>     ) -> np.ndarray:  # initial_guess_mode: InitialGuessModeType.USER_PROVIDED,
> ```

Yes this should be somewhere here.  keep initial_guess_mode as an entry of the method
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 378 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzM6yh4k0_nJzwkTzP:-NnzM6yh4k0_nJzwkTzQ:bsw9bys) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/inverse_kinematics.py#L378)):*
> ```Python
>                         Q_init = self.Q_init
>                     else:
>                         Q_init = self.model.Q_from_markers(self.initialize_markers[:, :, f : f + 1])
> ```

This should be generic for both for the two if cases for example: 

InitialGuessModeType.USER_PROVIDED
InitialGuessModeType.FROM_CURRENT_MARKERS

should work both for solve_frame_per_frame = True and False



_Code quote:_
```Python
                if self.initial_guess_mode == InitialGuessModeType.USER_PROVIDED:
                    Q_init = self.Q_init[:, f : f + 1]
                if self.initial_guess_mode == InitialGuessModeType.FROM_CURRENT_MARKERS:
                    Q_init = self.model.Q_from_markers(self.initialize_markers[:, :, f : f + 1])
                if self.initial_guess_mode == InitialGuessModeType.USER_PROVIDED_FIRST_FRAME_ONLY:
                    if f == 0:
                        Q_init = self.Q_init
                    else:
                        Q_init = Qopt[:, f - 1 : f]
                if self.initial_guess_mode == InitialGuessModeType.FROM_FIRST_FRAME_MARKERS:
                    if f == 0:
                        Q_init = self.Q_init
                    else:
                        Q_init = self.model.Q_from_markers(self.initialize_markers[:, :, f : f + 1])
```


<!-- Sent from Reviewable.io -->

2024-01-16 12:52 UTC, aaiaueil reviewed
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/132)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_numpy/initial_guess_mode_type.py` line 8 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzI_Ph-FgXrzqEXFZs:-NoHI9uiATJjINTZLlD-:b3vdgu8) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/initial_guess_mode_type.py#L8)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Put this in enums.py
</blockquote></details>

I get a circular import problem with import Joint when I put both classes in the same file. For now I keep them separated
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 72 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzIeFmDSjdUzqKs3H-:-NoGVsKJ8ndinzJn7des:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/inverse_kinematics.py#L72)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

What you wrote is not wrong but this would be more precise.
```python3
initial_guess_mode: InitialGuessModeType,
```
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 74 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzJ82r36n-9kqV4bVV:-NoGVvDI0FbwnOgUlVT9:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/inverse_kinematics.py#L74)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I believe this new entry is a mistake, this is a mistake to remove !!
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 132 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzJfAOBwkWM07cMU2P:-NoHHYuN5wnlFoV4cm_h:bxyf4zf) ([raw file](https://github.com/Ipuch/bioNC/blob/c8f5efb3c4742e2649473d5dbc53e643d36ab53d/bionc/bionc_numpy/inverse_kinematics.py#L132)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

You deleted this line that is absolutely major !!
It computes the Q from markers, and it can be used without providing 'initialize_markers'
in the case of "FROM_MARKERS", this function needs to be used.
</blockquote></details>

I kept the if loop to check that Q_init is not None for heatmaps, but self.model.Q_from_markers(...) is now used in get_Q_init_from_initial_guess_mode.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 253 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzKF_c-ninaEiVH_le:-NoGeQyx6Fv2eD3UvRTC:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/inverse_kinematics.py#L253)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Please displace this section of code in the method `solve`.
and encapsulate it in a method name  ̀get_Q_init_from_initial_guess_mode(...) `
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 317 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzKdbf8diHHy01QplI:-NoGgLl2A3Mzduuj6XQ2:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/inverse_kinematics.py#L317)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Yes this should be somewhere here.  keep initial_guess_mode as an entry of the method
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 378 at r1](https://reviewable.io/reviews/Ipuch/bioNC/132#-NnzM6yh4k0_nJzwkTzP:-NoGklrj2wXkU1UPROOk:b-8k7yqd) ([raw file](https://github.com/Ipuch/bioNC/blob/e21ac5eff36a1f0bb6991a47c84c171201c8d06c/bionc/bionc_numpy/inverse_kinematics.py#L378)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This should be generic for both for the two if cases for example: 

InitialGuessModeType.USER_PROVIDED
InitialGuessModeType.FROM_CURRENT_MARKERS

should work both for solve_frame_per_frame = True and False
</blockquote></details>

Is this urgent? I'm still not sure I understand how solving for all frames works and am running a bit out of time


<!-- Sent from Reviewable.io -->

2024-01-16 19:10 UTC, Ipuch approved these changes
> Reviewed 6 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/132)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aaiaueil)



<!-- Sent from Reviewable.io -->

2024-03-01 22:42 UTC, Ipuch commented
@aaiaueil up

2024-03-13 15:04 UTC, Ipuch requested changes
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/132)* status: 9 of 10 files reviewed, 7 unresolved discussions (waiting on @aaiaueil)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 72 at r2](https://reviewable.io/reviews/Ipuch/bioNC/132#-NoI04m6-l5qdGhbdNR2:-NssKaSO5WmhXWA3xGtV:b-megsir) ([raw file](https://github.com/Ipuch/bioNC/blob/408e09ecc2676bb1adcae1e245931c9fe2612bf7/bionc/bionc_numpy/inverse_kinematics.py#L72)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

yes, it shouldn't?
</blockquote></details>

Outdated
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 324 at r2](https://reviewable.io/reviews/Ipuch/bioNC/132#-NoI0ytV-Gel2dRDWx32:-NssKmGrAA67v7OGSDr6:b-ct852e) ([raw file](https://github.com/Ipuch/bioNC/blob/408e09ecc2676bb1adcae1e245931c9fe2612bf7/bionc/bionc_numpy/inverse_kinematics.py#L324)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

I'm not sure I understand, that's how it is coded at the moment.
</blockquote></details>

outdated - Already resolved 


<!-- Sent from Reviewable.io -->

2024-03-13 16:04 UTC, Ipuch requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/132)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @aaiaueil)

___
*[`tests/test_initial_guess_mode.py` line 18 at r6](https://reviewable.io/reviews/Ipuch/bioNC/132#-NssYUVr8GCNFuji-m40:-NssYUVr8GCNFuji-m41:brkb732) ([raw file](https://github.com/Ipuch/bioNC/blob/ca2aa9ac742aaff614f2198658b3997eb6888ca8/tests/test_initial_guess_mode.py#L18)):*
> ```Python
>     model = module.model_creation_from_measured_data()
>     markers = Markers.from_c3d(c3d_filename, usecols=model.marker_names_technical).to_numpy()
>     Q_INITIALIZE = model.Q_from_markers(markers[:, :, :])
> ```

no more needed to capitalize as this is not a global variable. Q\_initialize



_Code quote:_
```Python
Q_INITIALIZE
```


<!-- Sent from Reviewable.io -->

2024-03-13 16:04 UTC, Ipuch requested changes
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/132)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @aaiaueil)

___
*[`tests/test_initial_guess_mode.py` line 301 at r6](https://reviewable.io/reviews/Ipuch/bioNC/132#-NssYdld5m6K9vNjKLKT:-NssYdld5m6K9vNjKLKU:b-hnp8f2) ([raw file](https://github.com/Ipuch/bioNC/blob/ca2aa9ac742aaff614f2198658b3997eb6888ca8/tests/test_initial_guess_mode.py#L301)):*
> ```Python
> 
> 
> test_user_provided()
> ```

this line should not be here


<!-- Sent from Reviewable.io -->

2024-03-14 19:56 UTC, aaiaueil commented
Redundancy detected : 

In get_Q_init_from_initial_guess_mode lines 245 - 250
```
if experimental_markers is None:
    raise ValueError("Please provide experimental_markers in order to initialize the optimization")
if self.experimental_heatmaps is not None:
    raise ValueError(
        "Q_init cannot be computed from markers using heatmap data, please either provide marker data or change initialization mode"
    )
```

Seems to be redundant with line 102 in __init__ 

``` 
if experimental_markers is None and experimental_heatmaps is None:
    raise ValueError("Please feed experimental data, either marker or heatmap data")
```

If there is no data, either markers or heatmap, then ValueError("Please feed experimental data, either marker or heatmap data") is raised first, and it's not possible to have both markers and heatmap data provided.

2024-03-14 20:08 UTC, aaiaueil commented
Impossible error : 

```
  if (
      initial_guess_mode == InitialGuessModeType.FROM_CURRENT_MARKERS
      and experimental_markers.shape[2] != self.nb_frames
  ):
      raise ValueError("Please make sure initalize_markers contains all the frames")
```

Impossible to raise this error as self.nb_frames is defined as self.nb_frames = self.experimental_markers.shape[2]

To me this error is not needed

2024-03-14 20:39 UTC, aaiaueil reviewed
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/132)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 264 at r4](https://reviewable.io/reviews/Ipuch/bioNC/132#-Np_e3_bEuEoGQbglKcb:-NsxoHtd92ktIWLEXlkn:b9qad2v) ([raw file](https://github.com/Ipuch/bioNC/blob/35e473157eac75efdacfc2ee82c582e040517e39/bionc/bionc_numpy/inverse_kinematics.py#L264)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Why removing this, this makes no sens to have a Q_init of size [nb_q x nb_frames] when we have use the markers of the first frame to estimate the Q of the first frame too. 

It means the output size of this function, which is meant to get Q_init from the initial guess mode should respect the terminology of the provided enum.

If I provide InitialGuessModeType.FROM_FIRST_FRAME_MARKERS, I expect the size of Q_init to be [nb_q x 1] because the next estimates of frame too will be evaluated from last frame.
</blockquote></details>

this was fixed in my latest commit
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 284 at r4](https://reviewable.io/reviews/Ipuch/bioNC/132#-Np_eyv-DAnL-pS-iMnn:-Nsxo9V52ks4I6TH8Uog:b-vjuafy) ([raw file](https://github.com/Ipuch/bioNC/blob/35e473157eac75efdacfc2ee82c582e040517e39/bionc/bionc_numpy/inverse_kinematics.py#L284)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I disagree too because Q_init should be [nb_q x 1] or [nb_q] in that case ! That's may explain an error that wasn't raised when designing your tests.
</blockquote></details>

Fixed in latest commit as well
___
*[`examples/model_creation/marker_model.py` line 1 at r5](https://reviewable.io/reviews/Ipuch/bioNC/132#-Np_bfgh1OM01k7g_KaO:-NsxmCSt327XdsZP9qFS:brzknvq) ([raw file](https://github.com/Ipuch/bioNC/blob/eb05e339f3be4d8b9357830ea8d931295f7a87b3/examples/model_creation/marker_model.py#L1)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Why adding another model in model creation? Why not using one already existing ? If you give me a rationale for this, I can pass on this.
But if this was not absolutely necessary, please use another model in the new tests, and change the expected_values.
</blockquote></details>

Model was deleted
___
*[`examples/model_creation/marker_model.py` line 32 at r5](https://reviewable.io/reviews/Ipuch/bioNC/132#-Np_cAEo72REd_ZjQfSq:-NsxmGo35M6i6SbXAQ98:b1eci2u) ([raw file](https://github.com/Ipuch/bioNC/blob/eb05e339f3be4d8b9357830ea8d931295f7a87b3/examples/model_creation/marker_model.py#L32)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

If the model is necessary, this function is already implemented elsewhere in the lower_limb model I believe, please use/import it instead of duplicating code.
</blockquote></details>

Model was deleted so comment not up to date
___
*[`tests/test_initial_guess_mode.py` line 10 at r5](https://reviewable.io/reviews/Ipuch/bioNC/132#-Np_bH1T7uXz6QTRWwyG:-NsxmcJiEB6yBg2Fukbj:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/eb05e339f3be4d8b9357830ea8d931295f7a87b3/tests/test_initial_guess_mode.py#L10)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Capitalize all the letters of Q_initialize. Constants and global variables should declare all capitalized according to PEP8 style.
</blockquote></details>

Done.
___
*[`tests/test_initial_guess_mode.py` line 285 at r5](https://reviewable.io/reviews/Ipuch/bioNC/132#-Np_ai8V3oT-HMTBHtqn:-NsxoZZx5ncKUh08KSXt:b-gmwy0k) ([raw file](https://github.com/Ipuch/bioNC/blob/eb05e339f3be4d8b9357830ea8d931295f7a87b3/tests/test_initial_guess_mode.py#L285)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Should it be Q_init=Q_initialize[:,0:1]? Because we only need one frame here (?)

Thus, I believe, this case should throw/raise an error.
</blockquote></details>

Woops, my bad. I added a raise ValueError in inverse_kinematics.py and some tests in test_initial_guess_mode
___
*[`tests/test_initial_guess_mode.py` line 18 at r6](https://reviewable.io/reviews/Ipuch/bioNC/132#-NssYUVr8GCNFuji-m40:-NsxmfZaBwNVQh5aFgJ5:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/ca2aa9ac742aaff614f2198658b3997eb6888ca8/tests/test_initial_guess_mode.py#L18)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

no more needed to capitalize as this is not a global variable. Q\_initialize
</blockquote></details>

Done.
___
*[`tests/test_initial_guess_mode.py` line 301 at r6](https://reviewable.io/reviews/Ipuch/bioNC/132#-NssYdld5m6K9vNjKLKT:-NsxpRMlCjzorAxiCdMg:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/ca2aa9ac742aaff614f2198658b3997eb6888ca8/tests/test_initial_guess_mode.py#L301)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

this line should not be here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-15 15:43 UTC, Ipuch reviewed
> Reviewed 2 of 2 files at r7, 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/132)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @aaiaueil)



<!-- Sent from Reviewable.io -->

2024-03-15 16:12 UTC, Ipuch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/132#-:-Nt1sj91AX_OAjPdap-3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aaiaueil)



<!-- Sent from Reviewable.io -->

2024-03-15 16:12 UTC, merged