[wip] Modification on inverse kinematics to do some stat
Ipuch/bioNC pull request #92
Opened 2023-09-29 14:56 UTC by ANaaim

To follow the different idea.

2023-09-29 14:57 UTC, ANaaim commented
Forgot the link to the issues :  

#84

2023-10-02 15:36 UTC, Ipuch commented
Let me know when you want a review. 🙂

2023-10-13 14:12 UTC, Ipuch reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 66 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgdNBTY5MEnxqkD6YLw:-NgdNBTY5MEnxqkD6YLx:bsoojgz) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L66)):*
> ```Python
>     r = S(x0=Q_init, lbg=lbg, ubg=ubg)
> 
>     if S.stats()["success"] is False:
> ```

Pointing, look here for stats. :flags: 
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 346 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgdMkad7LGDKiw-LMoK:-NgdMkad7LGDKiw-LMoL:b4lahg4) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L346)):*
> ```Python
>                 lbg = np.concatenate((lbg, np.zeros(self.model.nb_segments * self.nb_frames)))
>                 ubg = np.concatenate((ubg, np.full(self.model.nb_segments * self.nb_frames, np.inf)))
>             r = _solve_nlp(method, nlp, Q_init, lbg, ubg, options)
> ```

r["stats"] may contain success or failure of the optimization.
you could save it into
self.stats=[]
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 432 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVb7Dy-vYG3d9weIgA:-NgVb7Dy-vYG3d9weIgB:b-6qc7s2) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L432)):*
> ```Python
>             and the marker with highest residual
>         """
>         from bionc.bionc_numpy.natural_coordinates import NaturalCoordinates
> ```

Already imported as NaturalCoordinatesNumpy
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 438 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVbMAI4zlUt80oUNZk:-NgVbMAI4zlUt80oUNZl:bl792us) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L438)):*
> ```Python
>         residuals_makers_xyz = dict()
>         residuals_joints = dict()
>         residuals_rigidity = dict()
> ```

I would rather write to be consistent with pyomeca

```python3
residuals_markers_norm = np.zeros((1, n_marker, n_frame))
residuals_markers_xyz = np.zeros((3, n_marker, n_frame))
residuals_joints = np.zeros((n_joint_constraints, n_frame)) 
residuals_rigidity = np.zeros((6, n_segment, n_frame))  or np.zeros((6 * n_segment, n_frame))
```

to handle global over all markers or all constraints i would fill these instead of having dict

```python3
total_residuals_markers = np.zeros((n_frame))
total_residuals_joints = np.zeros((n_frame)) 
total_residuals_rigidity = np.zeros((n_frame))
```



_Code quote:_
```Python
        residuals_markers = dict()
        residuals_makers_xyz = dict()
        residuals_joints = dict()
        residuals_rigidity = dict()
```
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 461 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVdDUIETnDfiT_aHGA:-NgVdDUIETnDfiT_aHGB:b9pfg3b) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L461)):*
> ```Python
>         for i in range(self.nb_frames):
>             # Rigidity constraint
>             phir_post_optim = self.model.rigid_body_constraints(NaturalCoordinates(self.Qopt[:, i]))
> ```

Fill first the individual residuals and then, later on, convert them into total residuals. But first do all the individual computations.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 468 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgdLyK507e8L_GlRqLF:-NgdLyK507e8L_GlRqLG:b-r0pn2c) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L468)):*
> ```Python
>             # Kinematics constraints (associated with the joint of the model)
>             phik_post_optim = self.model.joint_constraints(NaturalCoordinates(self.Qopt[:, i]))
>             residuals_joints["Global"][:, i] = np.sqrt(np.dot(phik_post_optim, phik_post_optim))
> ```

All the global together at the end, out of the for loop.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 473 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVdjcj-zK17KlY-i7Q:-NgVdjcj-zK17KlY-i7R:b-lygcz7) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L473)):*
> ```Python
>                 nb_constraint = self.model.joints[key].nb_constraints
>                 if nb_constraint > 0:
>                     residuals_joints[key][:, i] = phik_post_optim[
> ```

Treating with dict complexify the code for nothing.

Just fill joint constraints as in propose format in np.ndarray. It will be enough to monitor the results. [Njoints x Nframes]
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 482 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVeK1JA1cvSRs8uE2w:-NgVeK1JA1cvSRs8uE2x:bm4a5ar) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L482)):*
> ```Python
>                 self.experimental_markers[:, :, i], NaturalCoordinates(self.Qopt[:, i]), only_technical=True
>             )
>             residuals_markers["Global"][:, i] = np.sqrt(np.dot(phim_post_optim, phim_post_optim))
> ```

Global into a dedicated variable named 'total_residuals_markers' or 'total_marker_residual' ?
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 495 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVecfB4ypxXkLJT7Vm:-NgVecfB4ypxXkLJT7Vn:bqoqlv6) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L495)):*
> ```Python
>                 residuals_makers_xyz[key][:, i] = phim_post_optim[ind * 3 : (ind + 1) * 3]
>                 # Should we do this or do a huge matrix with all the residuals and then extract the max with a simple
>                 # np.args(np.max(big_matrix) ?
> ```

YES ! that's why keep the format into np.ndarray would be much more easy.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 522 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVet62AXCUmNmvTr0Q:-NgVet62AXCUmNmvTr0R:b-dr1470) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L522)):*
> ```Python
>         residuals["rigidity"] = residuals_rigidity
> 
>         self.output = dict(
> ```

Let's keep the dictionnary as simple as possible and as readable as possible

```python3
self.output = dict(
marker_residuals: np.ndarray = ...,
marker_residuals_xyz: np.ndarray = ...,
total_marker_residuals: np.ndarray = ...,
max_marker_distance: list[str] = ..., # len = nb frame
joint_constraints_defects: np.ndarray = ...,
max_joint_violation: list[str] = ..., # len = nb frame
total_joint_constraints_defects: np.ndarray = ...,
rigidbody_constraints_defects: np.ndarray = ...,
total_rigidbody_constraints_defects: np.ndarray = ...,
max_rigidbody_violation: list[str] = ...,  # len = nb frame
# try to intercept this output of the sovlers to save the messages
#
# message=[sol.message for sol in self.list_sol],
# status=[sol.status for sol in self.list_sol],
# success=[sol.success for sol in self.list_sol],   # True or False
#
)
```



<!-- Sent from Reviewable.io -->

2023-10-16 11:25 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 468 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgdLyK507e8L_GlRqLF:-NgsDzrS8LXdj91ephXJ:b9smp64) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L468)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

All the global together at the end, out of the for loop.
</blockquote></details>

Answer above 
Done


<!-- Sent from Reviewable.io -->

2023-10-16 13:36 UTC, ANaaim reviewed
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 66 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgdNBTY5MEnxqkD6YLw:-NgsOVGxAFaLk6jcTrIL:b3b9p7m) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L66)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Pointing, look here for stats. :flags:
</blockquote></details>

Done
But question about what we would liket to extract from S ==> currently only success but we could imagine to extract other parameter in the dictionary : to evaluate
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 346 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgdMkad7LGDKiw-LMoK:-NgsOiWP6FYccGdwAnZb:b-55x5dk) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L346)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

r["stats"] may contain success or failure of the optimization.
you could save it into
self.stats=[]
</blockquote></details>

Done but linked to the question above
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 432 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVb7Dy-vYG3d9weIgA:-Ngrl5lAEjzhCMhO807G:b-896fjx) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L432)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Already imported as NaturalCoordinatesNumpy
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 438 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVbMAI4zlUt80oUNZk:-NgsDjPc6qrfVh-MD_12:b-896fjx) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L438)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I would rather write to be consistent with pyomeca

```python3
residuals_markers_norm = np.zeros((1, n_marker, n_frame))
residuals_markers_xyz = np.zeros((3, n_marker, n_frame))
residuals_joints = np.zeros((n_joint_constraints, n_frame)) 
residuals_rigidity = np.zeros((6, n_segment, n_frame))  or np.zeros((6 * n_segment, n_frame))
```

to handle global over all markers or all constraints i would fill these instead of having dict

```python3
total_residuals_markers = np.zeros((n_frame))
total_residuals_joints = np.zeros((n_frame)) 
total_residuals_rigidity = np.zeros((n_frame))
```
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 461 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVdDUIETnDfiT_aHGA:-NgrwJxS3PKhdAuXlD6m:b1178xd) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L461)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Fill first the individual residuals and then, later on, convert them into total residuals. But first do all the individual computations.
</blockquote></details>

More logical to do the opposite ==> but every similar calculation is at the same place for better readability
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 473 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVdjcj-zK17KlY-i7Q:-NgsE3tT0r5MJAxJ5lVh:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L473)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Treating with dict complexify the code for nothing.

Just fill joint constraints as in propose format in np.ndarray. It will be enough to monitor the results. [Njoints x Nframes]
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 495 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVecfB4ypxXkLJT7Vm:-Ngsgo_B2xvwiQFbwcsg:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L495)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

YES ! that's why keep the format into np.ndarray would be much more easy.
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 522 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVet62AXCUmNmvTr0Q:-NgsgmbYDzHoo28YagH1:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L522)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Let's keep the dictionnary as simple as possible and as readable as possible

```python3
self.output = dict(
marker_residuals: np.ndarray = ...,
marker_residuals_xyz: np.ndarray = ...,
total_marker_residuals: np.ndarray = ...,
max_marker_distance: list[str] = ..., # len = nb frame
joint_constraints_defects: np.ndarray = ...,
max_joint_violation: list[str] = ..., # len = nb frame
total_joint_constraints_defects: np.ndarray = ...,
rigidbody_constraints_defects: np.ndarray = ...,
total_rigidbody_constraints_defects: np.ndarray = ...,
max_rigidbody_violation: list[str] = ...,  # len = nb frame
# try to intercept this output of the sovlers to save the messages
#
# message=[sol.message for sol in self.list_sol],
# status=[sol.status for sol in self.list_sol],
# success=[sol.success for sol in self.list_sol],   # True or False
#
)
```

</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-16 13:38 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 430 at r2](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngsh74w0aMjn3kXfsmx:-Ngsh74w0aMjn3kXfsmy:bogzmfx) ([raw file](https://github.com/Ipuch/bioNC/blob/5286c11346b3eb30a64114cc51b8efd75fe3d62a/bionc/bionc_numpy/inverse_kinematics.py#L430)):*
> ```Python
>         self.output: dict()
>             The output of least_square function, such as number of iteration per frames,
>             and the marker with highest residual
> ```

Should we describe each entry of the dictionary ? if yes what should it look like in the docstring ? 


<!-- Sent from Reviewable.io -->

2023-10-17 06:20 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 482 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVeK1JA1cvSRs8uE2w:-NgwHiUh9OevtIMcLHl4:b7a8ivj) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L482)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Global into a dedicated variable named 'total_residuals_markers' or 'total_marker_residual' ?
</blockquote></details>

Done ==> maybe we need to chose what word should be plural and what word should not. 


<!-- Sent from Reviewable.io -->

2023-10-17 13:25 UTC, Ipuch reviewed
looks good so far !!
juste missing test and we are good to merge :
get a look into test_inverse_kinematics_class():  

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92#-:-Ngxmz5K8tMnLXoN07F9:b5sxrrj)* status: all files reviewed, 11 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 482 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVeK1JA1cvSRs8uE2w:-Ngxluqh2fPFz8aQj3PI:b-x9ugqn) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L482)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Done ==> maybe we need to chose what word should be plural and what word should not.
</blockquote></details>

total_marker_residuals
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 430 at r2](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngsh74w0aMjn3kXfsmx:-Ngso3I-D3NAaF3Ft4wZ:b-9st4fy) ([raw file](https://github.com/Ipuch/bioNC/blob/5286c11346b3eb30a64114cc51b8efd75fe3d62a/bionc/bionc_numpy/inverse_kinematics.py#L430)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Should we describe each entry of the dictionary ? if yes what should it look like in the docstring ?
</blockquote></details>

```python3
 """
    Returns
    -------
    dict[str, np.ndarray | list[str]]
        Processed data with the following keys:
        - 'result_1' : np.ndarray
            A numpy array with processed data.
        - 'result_2' : list[str]
            A list of processed string data.
    """

```
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 204 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxkLOlAnLM_g2Hm-aT:-NgxkLOlAnLM_g2Hm-aU:b-9i4i5b) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L204)):*
> ```Python
>         self.nb_markers = self.experimental_markers.shape[1]
> 
>         self.success_optim = None
> ```

self.success_optim=[]
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 328 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxkNzV8I4Ks82X9y0Z:-NgxkNzV8I4Ks82X9y0_:b-mu0t41) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L328)):*
> ```Python
>                 g=_mx_to_sx(constraints, [self._vert_Q_sym]) if self.use_sx else constraints,
>             )
>             self.success_optim = []
> ```

remove this line
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 444 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxkofg532AYR-21hiM:-Ngxkofg532AYR-21hiN:b-dzjsxo) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L444)):*
> ```Python
>         nb_joints_constraints = 0
>         for ind, key in enumerate(self.model.joint_names):
>             nb_joints_constraints += self.model.joints[key].nb_constraints
> ```

biomechmodel.nb_joint_cosntraints ?
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 445 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxks4k5vqfcFgN6pqd:-Ngxks4k5vqfcFgN6pqe:bnkhfid) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L445)):*
> ```Python
>         for ind, key in enumerate(self.model.joint_names):
>             nb_joints_constraints += self.model.joints[key].nb_constraints
>         nb_segments = len(self.model.segment_names)
> ```

biomechmodel.nb_segments ?
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 480 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxl4pU-fw2VrF57cmn:-Ngxl4pU-fw2VrF57cmo:bu4q84f) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L480)):*
> ```Python
>                 nb_constraint = self.model.joints[key].nb_constraints
>                 if nb_constraint > 0:
>                     residuals_joints[nb_temp_constraint : nb_temp_constraint + nb_constraint, i] = phik_post_optim[
> ```

What you are trying to do is to get the slicing of such as  -> slice(3,5).
biomechmodel.joint_constraint_index("knee" or 2)   -> slice(3, 5).
it's in the folder protocol.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 489 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxmO0A42AV78wlEnXY:-NgxmO0A42AV78wlEnXZ:bri2c5e) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L489)):*
> ```Python
>             for ind, key in enumerate(self.model.marker_names_technical):
>                 residuals_markers_norm[:, ind, i] = np.sqrt(
>                     np.dot(phim_post_optim[ind * 3 : (ind + 1) * 3], phim_post_optim[ind * 3 : (ind + 1) * 3])
> ```

maybe a reshape(3,n) would ease the reading.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 494 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxmYftB8G5UmazwaeS:-NgxmYfu-dZArGbMsrWR:b-7nssrx) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L494)):*
> ```Python
> 
>         # Calculation of the residual on all frames
>         all_frames_residuals_markers = np.sqrt(np.dot(total_residuals_markers, np.transpose(total_residuals_markers)))
> ```

Directly use the final names in the final dict.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 508 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxm22N7GEst0YBk9lR:-Ngxm22N7GEst0YBk9lS:b73bev6) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L508)):*
> ```Python
> 
>         # Create a list of marker, segment and joint from the indices
>         toto = self.model.marker_names_technical
> ```

toto is not valid name :)
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 532 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxmqxR4rasePjDFK4C:-NgxmqxR4rasePjDFK4D:bzbdwul) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L532)):*
> ```Python
>             all_frames_residuals_rigity=all_frames_residuals_rigity,
>             max_rigidbody_violation=max_rigidbody_violation,
>             success=success,
> ```

Remove compression along time.


<!-- Sent from Reviewable.io -->

2023-10-30 10:01 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 204 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxkLOlAnLM_g2Hm-aT:-Ni-0yvzDO8Rd2RU5BSW:b-896fjx) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L204)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

self.success_optim=[]
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-30 10:02 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 328 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxkNzV8I4Ks82X9y0Z:-Ni-18ks7gjOtlg3WMT0:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L328)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove this line
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-30 10:10 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 444 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxkofg532AYR-21hiM:-Ni-2vGADVxSE9bDeRgI:b-896fjx) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L444)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

biomechmodel.nb_joint_cosntraints ?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-30 14:11 UTC, ANaaim commented
First version of the test has been done not sure if at the right place.

2023-10-30 17:53 UTC, Ipuch reviewed
Tests are perfect, This starts to look real good to me ! Almost Done !

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92#-:-Ni0hqgVE_KTl3sfHizO:b-2ejkko)* status: all files reviewed, 3 unresolved discussions (waiting on @ANaaim)



<!-- Sent from Reviewable.io -->

2023-11-03 12:37 UTC, Ipuch commented
Do you think you'll be able to solve the three comments left for the next Tuesday?

2023-11-03 12:39 UTC, ANaaim commented
can do it now





<!-- Sent from Reviewable.io -->

2023-11-03 12:43 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 480 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxl4pU-fw2VrF57cmn:-Ni-52Az92xarMHHtQFd:b-relz8g) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L480)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

What you are trying to do is to get the slicing of such as  -> slice(3,5).
biomechmodel.joint_constraint_index("knee" or 2)   -> slice(3, 5).
it's in the folder protocol.
</blockquote></details>

I did not found this function in bionc/protocols/biomechanical_model.py.... Was it suppose to be a new function ? 


<!-- Sent from Reviewable.io -->

2023-11-03 12:43 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 489 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxmO0A42AV78wlEnXY:-Ni-F79YEIB9aJokqfBa:b-lqm5qo) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L489)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

maybe a reshape(3,n) would ease the reading.
</blockquote></details>

Not sure if i remember well but this should have a shape [1,nb_marker,nb_frame] or [3,nb_marker,nb_frame] ? 


<!-- Sent from Reviewable.io -->

2023-11-03 12:43 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 489 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxmO0A42AV78wlEnXY:-NiKCTxgDCgOybjOwyWM:b-3u1jv6) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L489)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Not sure if i remember well but this should have a shape [1,nb_marker,nb_frame] or [3,nb_marker,nb_frame] ?
</blockquote></details>

Question to answer


<!-- Sent from Reviewable.io -->

2023-11-03 12:45 UTC, ANaaim reviewed
Which three comments ? 

> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92#-:-NiKBdAm8RS5ZngYebY9:b-p46jh9)* status: all files reviewed, 4 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 482 at r1](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgVeK1JA1cvSRs8uE2w:-Ni-BT1H06fh5x-Nov8-:btayja2) ([raw file](https://github.com/Ipuch/bioNC/blob/3c9acb46567c234164e7fabc727462fecc5cb4b0/bionc/bionc_numpy/inverse_kinematics.py#L482)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

total_marker_residuals
</blockquote></details>

Done : also for other variable for coherence
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 430 at r2](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngsh74w0aMjn3kXfsmx:-NiKBfaN1_Hoveu5X510:b-896fjx) ([raw file](https://github.com/Ipuch/bioNC/blob/5286c11346b3eb30a64114cc51b8efd75fe3d62a/bionc/bionc_numpy/inverse_kinematics.py#L430)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

```python3
 """
    Returns
    -------
    dict[str, np.ndarray | list[str]]
        Processed data with the following keys:
        - 'result_1' : np.ndarray
            A numpy array with processed data.
        - 'result_2' : list[str]
            A list of processed string data.
    """

```
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 530 at r2](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngslilx7IoPOFAeEnos:-Ngslilx7IoPOFAeEnot:b-nrdx4k) ([raw file](https://github.com/Ipuch/bioNC/blob/5286c11346b3eb30a64114cc51b8efd75fe3d62a/bionc/bionc_numpy/inverse_kinematics.py#L530)):*
> ```Python
>             # success=[sol.success for sol in self.list_sol],
>         )
>         return self.output
> ```

Question about testing : What should we test : 
1) If all key are generated 
2) If the different key have the correct size 
3) The value of the constraint ? All of them ?

==> In a way if we test all the value we test everything but it seems a little cumbersome to me.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 445 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxks4k5vqfcFgN6pqd:-Ni-3Hzy0UEPKvbjnPj_:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L445)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

biomechmodel.nb_segments ?
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 480 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxl4pU-fw2VrF57cmn:-NiKCQ0o-QARI4OKCcaJ:b-3u1jv6) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L480)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

I did not found this function in bionc/protocols/biomechanical_model.py.... Was it suppose to be a new function ?
</blockquote></details>

Question to answer
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 494 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxmYftB8G5UmazwaeS:-Ni-9eRU1jveweVnB6Xw:bl7spb2) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L494)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Directly use the final names in the final dict.
</blockquote></details>

Not sure to remember what was suppose to be done there but as we removed these value from the dictionary seems irrelevant now
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 508 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxm22N7GEst0YBk9lR:-Ni-99nO-xm-QL_klT9Q:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L508)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

toto is not valid name :)
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 532 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxmqxR4rasePjDFK4C:-Ni-9TEB8HsAt_ram5BU:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L532)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Remove compression along time.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-03 13:04 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 489 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxmO0A42AV78wlEnXY:-NiKH4BmE_MGnsn8tCKc:b7kfwgz) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L489)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Question to answer
</blockquote></details>

Done : i am taking full responsability ^^


<!-- Sent from Reviewable.io -->

2023-11-03 14:16 UTC, ANaaim reviewed
All done

> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92#-:-NiKXa6x-rW7qs_Z73aR:b-cw6y2k)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 530 at r2](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngslilx7IoPOFAeEnos:-NiKK7Ib3Qh4khDjj291:bb7f2mf) ([raw file](https://github.com/Ipuch/bioNC/blob/5286c11346b3eb30a64114cc51b8efd75fe3d62a/bionc/bionc_numpy/inverse_kinematics.py#L530)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Question about testing : What should we test : 
1) If all key are generated 
2) If the different key have the correct size 
3) The value of the constraint ? All of them ?

==> In a way if we test all the value we test everything but it seems a little cumbersome to me.
</blockquote></details>

done
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 480 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxl4pU-fw2VrF57cmn:-NiKXYxO0MQaN9-r98nK:b-e7xwj5) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L480)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Question to answer
</blockquote></details>

Done with testing
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 494 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-NgxmYftB8G5UmazwaeS:-NiKXUKZAmiFVGNPiXhq:bt1re42) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L494)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Not sure to remember what was suppose to be done there but as we removed these value from the dictionary seems irrelevant now
</blockquote></details>

Done (but nothing was necessary)


<!-- Sent from Reviewable.io -->

2023-11-03 14:44 UTC, Ipuch requested changes
> Reviewed 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 480 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxl4pU-fw2VrF57cmn:-NiKcOaICDSPyRhFyYzL:bxqzles) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L480)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Done with testing
</blockquote></details>

I'm still not convince by this implementation, I feel like the list around the loop are not necessary anymore. Also the enumerate may not be necessary.
And insert self.model.joint_constraints_index(key) in a variable like "joint_constraints_slice = "
___
*[`bionc/protocols/biomechanical_model.py` line 589 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKaOC-BUqpXPtEOqEO:-NiKaOC-BUqpXPtEOqEP:b55bmxl) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L589)):*
> ```Python
>         """
>         if isinstance(joint_id, int):
>             # We check that the joint index exists
> ```

There are too many comments, the code should as self-explanatory as possible, i.e. spend more time to choose your variable names.
Because when maintaining the code, variables may change, behavior also and comments are most of the time not updated. 

So remove the comments.
___
*[`bionc/protocols/biomechanical_model.py` line 593 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKaqsx43qAdRRg6BIx:-NiKaqsx43qAdRRg6BIy:bd7h76k) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L593)):*
> ```Python
>                 raise ValueError("The joint index " + str(joint_id) + " does not exist")
> 
>         if isinstance(joint_id, str):
> ```

This should be the first test as play with int after all.
___
*[`bionc/protocols/biomechanical_model.py` line 597 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKb1nJ4_Ypv_T72JYy:-NiKb1nKDSKb-Qw3rOKC:b-piiuvk) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L597)):*
> ```Python
>             if joint_id not in self.joint_names:
>                 raise ValueError("The joint name " + joint_id + " does not exist")
>             else:
> ```

remove else
___
*[`bionc/protocols/biomechanical_model.py` line 601 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKbCxqEFoT20MVpRQo:-NiKbCxqEFoT20MVpRQp:bj85m0n) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L601)):*
> ```Python
> 
>         # We extract all the number of constraints of each joint in a ndarray of size nb_joints
>         list_nb_constraint_joint = np.zeros(self.nb_joints)
> ```

this is not a list but an array. use integers to count at each loop until you reach the joint.
you'll get start_slice and 
add the number of constraint of considered joint to the counter.
___
*[`bionc/protocols/biomechanical_model.py` line 602 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKbO5iB9nxOtg-LFVp:-NiKbO5iB9nxOtg-LFVq:b-4l2a20) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L602)):*
> ```Python
>         # We extract all the number of constraints of each joint in a ndarray of size nb_joints
>         list_nb_constraint_joint = np.zeros(self.nb_joints)
>         for ind, key in enumerate(self.joint_names):
> ```

i, joint_name


<!-- Sent from Reviewable.io -->

2023-11-03 14:54 UTC, ANaaim reviewed
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 480 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxl4pU-fw2VrF57cmn:-NiKdWN_5JgZ6jPcIdHJ:b-pwoal2) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L480)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I'm still not convince by this implementation, I feel like the list around the loop are not necessary anymore. Also the enumerate may not be necessary.
And insert self.model.joint_constraints_index(key) in a variable like "joint_constraints_slice = "
</blockquote></details>

The list around the loop is for later ==> we need to be able to know from the indexes of the max constraint on l.522. I can try to find a cleaner methods.


<!-- Sent from Reviewable.io -->

2023-11-03 15:12 UTC, ANaaim commented
*[`bionc/protocols/biomechanical_model.py` line 602 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKbO5iB9nxOtg-LFVp:-NiKjIvM-nyt6o51fwV9:b-z1ia1) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L602)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

i, joint_name
</blockquote></details>

I do not like using i ==> let's change to ind_joint, name_joint ? 


<!-- Sent from Reviewable.io -->

2023-11-03 15:21 UTC, ANaaim commented
*[`bionc/protocols/biomechanical_model.py` line 602 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKbO5iB9nxOtg-LFVp:-NiKlbhCBkpZGn024Fxm:b31oso) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L602)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

I do not like using i ==> let's change to ind_joint, name_joint ?
</blockquote></details>

Done without i 


<!-- Sent from Reviewable.io -->

2023-11-03 15:21 UTC, ANaaim reviewed
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/protocols/biomechanical_model.py` line 589 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKaOC-BUqpXPtEOqEO:-NiKj-xk0YTiIGCPA_FN:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L589)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

There are too many comments, the code should as self-explanatory as possible, i.e. spend more time to choose your variable names.
Because when maintaining the code, variables may change, behavior also and comments are most of the time not updated. 

So remove the comments.
</blockquote></details>

Done
___
*[`bionc/protocols/biomechanical_model.py` line 593 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKaqsx43qAdRRg6BIx:-NiKlaci2f1VhCNOL61S:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L593)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This should be the first test as play with int after all.
</blockquote></details>

Done
___
*[`bionc/protocols/biomechanical_model.py` line 597 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKb1nJ4_Ypv_T72JYy:-NiKlFbnBqf3eJLQDX4x:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L597)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove else
</blockquote></details>

Done
___
*[`bionc/protocols/biomechanical_model.py` line 601 at r7](https://reviewable.io/reviews/Ipuch/bioNC/92#-NiKbCxqEFoT20MVpRQo:-NiKkxjH67d3Tp2MOaq0:b-896fjb) ([raw file](https://github.com/Ipuch/bioNC/blob/8def597aac300bd8e95ae86e115d780f117bd916/bionc/protocols/biomechanical_model.py#L601)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

this is not a list but an array. use integers to count at each loop until you reach the joint.
you'll get start_slice and 
add the number of constraint of considered joint to the counter.
</blockquote></details>

Done 


<!-- Sent from Reviewable.io -->

2023-11-03 16:21 UTC, ANaaim commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 480 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxl4pU-fw2VrF57cmn:-NiKxUcb8uhlV62HyYPv:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L480)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

The list around the loop is for later ==> we need to be able to know from the indexes of the max constraint on l.522. I can try to find a cleaner methods.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-03 17:13 UTC, Ipuch requested changes
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92)* status: all files reviewed, 3 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 480 at r5](https://reviewable.io/reviews/Ipuch/bioNC/92#-Ngxl4pU-fw2VrF57cmn:-NiKx22t5e0u3T6aX_aa:b-1dms87) ([raw file](https://github.com/Ipuch/bioNC/blob/4b8c5697675e9ef900882e09054140dc6bac14a0/bionc/bionc_numpy/inverse_kinematics.py#L480)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

The list around the loop is for later ==> we need to be able to know from the indexes of the max constraint on l.522. I can try to find a cleaner methods.
</blockquote></details>

It feels like this is just a 


<!-- Sent from Reviewable.io -->

2023-11-03 17:13 UTC, Ipuch approved these changes
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ANaaim)



<!-- Sent from Reviewable.io -->

2023-11-03 17:14 UTC, merged