Add HMP constraints to InverseKinematics
Ipuch/bioNC pull request #98
Opened 2023-10-11 09:00 UTC by aaiaueil

2023-10-16 11:48 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 230 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgZPsP6D6yfpJlii4PN:-NgsIySiEJHkm76z3t1b:bboxo1f) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L230)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

self._markers_sym = MX.sym("markers", (3, self.nb_markers))
self._camera__parameters_sym = MX.
self._gaussian_parameters_sym = MX.

example:
def addition(a,b,c):
return a+b
</blockquote></details>

we should verify here that the symbolic variables I created have the appropriate shape depending on what they do afterwards


<!-- Sent from Reviewable.io -->

2023-10-16 11:49 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 195 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgZOEvj0jWnZ3zLeSxn:-NgsJHzEEsojMm7qiom3:b-uo7qo8) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L195)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Use self.experimental_markers is None as boolean.
</blockquote></details>

Wouldn't it be better to use self.experimental_heatmaps is not None as a boolean to indicate we use experimental heatmaps? Might be easier to understand


<!-- Sent from Reviewable.io -->

2023-10-16 12:38 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 520 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgZX4Gf40maDfLX4YdM:-NgsTO7DBVb_XlqsWA4e:b6jlvjs) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L520)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

camera_mx, gaussian_mx as entry.
</blockquote></details>

Putting it here so we can discuss it later : as my prpblem is under-constrained, some markers are used twice to build the model. For example, 'right_knee' is used to build segment right thigh and segment right shank. I don't want right_knee to weight twice in the optimization, how should I do? Should I build the model by doing  model["RSHANK"].add_marker(right_knee) for the shank only and not for the right hip, or should I add said marker for both segments and add conditions in the optimization?


<!-- Sent from Reviewable.io -->

2023-10-16 13:50 UTC, Ipuch commented
Nothing was pushed, Is that normal ? I would expect at least one commit to be pushed, after my review to turn the PR into RTR.

2023-10-17 13:16 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 158 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVkIiT6xRtdIuk3r55:-NgmvFAi8scGzHmI787e:bne9ccx) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L158)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

We need a discussion on the format of your data to simplify as much as possible the code. 
This is clearly not acceptable to add string as entry.

You have camera parameters and Gaussian parameters for each marker for each frame

experimental_heat_map_parameters: 
```python
dict(
camera_parameters= 3 x 4 x n_camera,
gaussian_parameters= 5 x n_marker x n_frame x n_camera,
)
```
</blockquote></details>

Modification made in the code calling the IK class.
Added experimental_heatmaps as a dictionary in the IK class initialization


<!-- Sent from Reviewable.io -->

2023-10-17 13:16 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 6 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVizIg2u3T90xtrsJ8:-NgcKKwkBZnkVlNiKNjE:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L6)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

ezc3d should not be imported.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 13:16 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 15 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVj6H5Bg6ffLAPnKHf:-NgcKK0JBwUpNtDzIW1L:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L15)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

You've blacked the wrong way.

black . - l120

Please restore all the line ...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 13:16 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 18 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVjDtREHqoz4wtx4Rs:-NgcKGiO-t3JWrZRfvsC:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L18)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 13:16 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 194 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVjPYD9DTJy3oPUllf:-NgmyO0809cptOFU6Agy:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L194)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Unblack
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 13:17 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 231 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgZP8ZpEr-9FahR3oHc:-Ngmzlj6DhE-wM_gYzfU:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L231)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

change the boolean
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 13:17 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 233 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgZPBIg3mFZmClf93Fy:-Ngn0a7fCd_PXg4nq1kV:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L233)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

self.experimental_heat_map_paremeters["gaussian_parameters"].shape[2]
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 13:17 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 277 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgZQseA8TzlEC7BzBfC:-Ngn4ebC9X0YzmbSKWxd:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L277)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

[self._Q_sym, self._markers_sym, self._camera_parameter_sym, self._gaussian_parameter_sym],
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 13:17 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 397 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgZS-aU6_mtxLg8GvPh:-NgrYEXUDsBUkQItdoL-:bbxjgp1) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L397)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

objective = self._objective_function(
self._Q_sym, 
self.experimental_markers[:, :, f] if experimental is None [], 
self.camera_parameters[:,:,:] if experimental_hmp is None [], 
self.gaussian_parameters[:,:,f,:] if experimental_hmp is None [], 
)

def addition(a,b,c,d):
return a_sym + 1 + 2 + 3
</blockquote></details>

Alex and Anais talking there : Should we mofify also the natural_marker.constraint (l.139) to be able to adapt to different input value ? We can discuss it tomorrow. 


<!-- Sent from Reviewable.io -->

2023-10-17 13:17 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 672 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVlhtgCAAPRqmVLjll:-NgsTKmK8xMBVLw1f7h6:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L672)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 14:27 UTC, Ipuch requested changes
Looks good so far ! 

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98#-:-Ngy1FcD3FElx4bRJGIe:b-xenvuu)* status: all files reviewed (commit messages unreviewed), 37 unresolved discussions (waiting on @aaiaueil)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 86 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngxrci_1QAvaIdGgokd:-Ngxrci_1QAvaIdGgoke:b15q7pj) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L86)):*
> ```Python
> 
> 
> def _compute_phim_hmp(X, cal, ratio, amp, pos, sigma):
> ```

documentation

clarify, write a doc.

put it out of the class.

\_compute\_confidence\_value\_of\_one\_heatmap(model\_marker, ...)

model\_markers(Q\_sym)

model\_markers: MX  
symbolic Homogenous of coordinate of model markers  
camera\_calibration\_matrix: np.ndarray  
....  
ratio: float  
....  
gaussian\_magnitude: float  
....  
gaussian\_center: np.ndarray  
... maybe add coordinate
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 132 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxpBMw0E8x6E-Lb2fk:-NgxpBMw0E8x6E-Lb2fl:b-6nzv6v) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L132)):*
> ```Python
> ]
> kp2name = dict(zip(ind_name, param_name))
> name2kp = dict(zip(param_name, ind_name))
> ```

Remove this.



_Code quote:_
```Python
ind_name = [i for i in range(26)]
param_name = [
    "nose",
    "left_eye",
    "right_eye",
    "left_ear",
    "right_ear",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
    "neck",
    "top_head",
    "left_Btoe",
    "left_Stoe",
    "left_heel",
    "right_Btoe",
    "right_Stoe",
    "right_heel",
    "chest",
]
kp2name = dict(zip(ind_name, param_name))
name2kp = dict(zip(param_name, ind_name))
```
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 145 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxrgSa6y8pEVOXwCIK:-NgxrgSa6y8pEVOXwCIL:b-ah0f7j) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L145)):*
> ```Python
>     experimental_markers : np.ndarray | str
>         The experimental markers (3xNxM numpy array), or a path to a c3d file
>     experimental_heatmaps : dict
> ```

dict[str, np.ndarray]
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 188 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngxrn7R7zaODvSMMEld:-Ngxrn7R7zaODvSMMEle:b-z4o118) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L188)):*
> ```Python
>         model: BiomechanicalModel,
>         experimental_markers: np.ndarray | str = None,
>         experimental_heatmaps: dict | str = None,
> ```

remove str and complete with dict[str, np.ndarray]
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 225 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxsOzn7Y4CzIrquPx9:-NgxsOzn7Y4CzIrquPxA:bb7i0y4) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L225)):*
> ```Python
>         if experimental_markers is None and experimental_heatmaps is None:
>             raise ValueError("Please feed experimental data, either marker or heatmap data")
>         elif experimental_markers is not None and experimental_heatmaps is not None:
> ```

if 
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 227 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxsXv32fZV2e8L_maP:-NgxsXv32fZV2e8L_maQ:b-gb6pte) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L227)):*
> ```Python
>         elif experimental_markers is not None and experimental_heatmaps is not None:
>             raise ValueError("Please choose between marker data and heatmap data")
>         elif isinstance(experimental_markers, str):
> ```

if experimental_markers is not None:
...

if heatmaps is not None:
...
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 239 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxtPwB8p8JROZR-N3P:-NgxtPwB8p8JROZR-N3Q:bt0iifo) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L239)):*
> ```Python
>         elif isinstance(experimental_heatmaps, dict):
>             if solve_frame_per_frame is False:
>                 raise ValueError("Heatmap optimisation can only be performed frame by frame right now")
> ```

NotImplementedError
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 247 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxuwJpE_WBOArdJR_i:-NgxuwJpE_WBOArdJR_j:bhio0pj) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L247)):*
> ```Python
> 
>         if Q_init is None and self.experimental_heatmaps is None:
>             self.Q_init = self.model.Q_from_markers(self.experimental_markers[:, :, :])
> ```

triangulated_markers ?? 
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 256 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngxwgsc4Fc0Gm4eW5cY:-Ngxwgsc4Fc0Gm4eW5cZ:b-9je5kp) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L256)):*
> ```Python
>         self.segment_determinants = None
>         self._Q_sym, self._vert_Q_sym = self._declare_sym_Q()
> ```


if experimental_markers is not None
self.nb_frames = 
else:
self.nb_frames = 

if
self.nb_markers = 
else:
self.nb_markers =

if experimental_markers is not None
self.nb_camera = 0
else:
self.nb_frames = XX


Once all attributes are filled
Create the corresponding mx.


And find a way to concatenate dimensions of mx symbolic into a 2d matrix.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 259 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxwOLR0Lf0iXXzm9j9:-NgxwOLR0Lf0iXXzm9jA:b-s6e5nm) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L259)):*
> ```Python
>         if experimental_markers is None:
>             self.nb_frames = self.experimental_heatmaps["gaussian_parameters"].shape[2]
>             self.nb_markers = self.experimental_heatmaps["gaussian_parameters"].shape[1]
> ```

self.nb_camera = ...
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 267 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxwGJK4jVqbPo-L_vY:-NgxwGJK4jVqbPo-L_vZ:bxj2i6x) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L267)):*
> ```Python
>                 5,
>                 self.nb_markers,
>                 self.nb_frames,
> ```

remove nb_frame
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 279 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngxwc9r-lvnsITL1L_e:-Ngxwc9r-lvnsITL1L_f:btmyv86) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L279)):*
> ```Python
>             self._objective_function = None
> 
>         elif experimental_heatmaps is None:
> ```

is not None
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 413 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxyzH23I1sTVmC-zpH:-NgxyzH23I1sTVmC-zpI:bdgl31p) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L413)):*
> ```Python
>                     self._Q_sym,
>                     self.experimental_markers[:, :, f],
>                     self.camera_parameters,
> ```

reshape camera_param [...]

2023-10-23 11:45 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 256 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngxwgsc4Fc0Gm4eW5cY:-NhRLENi-yD9JiVuHJtx:bbo9vw4) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L256)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

if experimental_markers is not None
self.nb_frames = 
else:
self.nb_frames = 

if
self.nb_markers = 
else:
self.nb_markers =

if experimental_markers is not None
self.nb_camera = 0
else:
self.nb_frames = XX


Once all attributes are filled
Create the corresponding mx.


And find a way to concatenate dimensions of mx symbolic into a 2d matrix.
</blockquote></details>

I would like to double check with you I didn't do something too random


<!-- Sent from Reviewable.io -->

2023-10-23 11:46 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 259 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxwOLR0Lf0iXXzm9j9:-NhQsiQODSxoNquqSzSr:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L259)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

self.nb_camera = ...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-23 12:59 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 413 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxyzH23I1sTVmC-zpH:-NhRXI7s9EfjvzSciUyf:b-lqtc6x) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L413)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

reshape camera_parameters to fit the shape of the mx size
</blockquote></details>

wouldn't it be more consistent if camera_parameters.shape was nb_cameras x 3 x4 instead of 3 x 4 x nb_cameras, especially for reshaping afterwards? Reshaping in 2D would give something like nb_cameras x 12 and would be easier to understand/visualize in my opinion


<!-- Sent from Reviewable.io -->

2023-10-23 14:56 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 132 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxpBMw0E8x6E-Lb2fk:-NhS1LbvDHPFthtzr7-_:bfvb1i5) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L132)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Remove this.
</blockquote></details>

I'm still not sure how I can do without it...


<!-- Sent from Reviewable.io -->

2023-10-24 07:41 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 132 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxpBMw0E8x6E-Lb2fk:-NhVcQSL-YOngUZ2lTeB:b-eyejz) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L132)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

I'm still not sure how I can do without it...
</blockquote></details>

or should I code it myself directly in biomechanical_model class?


<!-- Sent from Reviewable.io -->

2023-10-24 07:51 UTC, aaiaueil reviewed
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98)* status: all files reviewed (commit messages unreviewed), 37 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 190 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgZMnIK3YZJs_2ATQj1:-NhQiw_k3CeuNL15Mwfp:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L190)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

```python3
if experimental_markers is None and experimental_heat_map is None
      raise ValueError("Please feed some experimental data ...)
if experimental_makers and experimental_heat_map:
     raise ValueError("Please choose either markers or heat map but not both")

if experimental_markers:
...
if experimental_heat_map_parameters:
      if isinstance(..., dict)  and "camera_parameters" in tata.keys()

```
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 397 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgZS-aU6_mtxLg8GvPh:-NhVeUDa4DX5RcVwOtS9:b-hyiwrc) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/inverse_kinematics.py#L397)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

Alex and Anais talking there : Should we mofify also the natural_marker.constraint (l.139) to be able to adapt to different input value ? We can discuss it tomorrow.
</blockquote></details>

could not have it to work like this, would be nice to have your opinion on it
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 86 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngxrci_1QAvaIdGgokd:-NhVWIlI5e16vCTdwwaM:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L86)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

documentation

clarify, write a doc.

put it out of the class.

\_compute\_confidence\_value\_of\_one\_heatmap(model\_marker, ...)

model\_markers(Q\_sym)

model\_markers: MX  
symbolic Homogenous of coordinate of model markers  
camera\_calibration\_matrix: np.ndarray  
....  
ratio: float  
....  
gaussian\_magnitude: float  
....  
gaussian\_center: np.ndarray  
... maybe add coordinate
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 145 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxrgSa6y8pEVOXwCIK:-NhQeyR8Dm-tlkmRyJ4J:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L145)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

dict[str, np.ndarray]
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 188 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngxrn7R7zaODvSMMEld:-NhQgNWo2HLrB7Nf8tdE:btt6opo) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L188)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove str and complete with dict[str, np.ndarray]
</blockquote></details>

shouldn't I leave str = None ? I get an error saying "non-default argument follows default argument" when I remove str = None
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 225 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxsOzn7Y4CzIrquPx9:-NhQjEY22FaCPlLX5Wx_:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L225)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

if
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 227 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxsXv32fZV2e8L_maP:-NhQjGxo8p4_gzQOhUUa:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L227)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

if experimental_markers is not None:
...

if heatmaps is not None:
...
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 239 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxtPwB8p8JROZR-N3P:-NhQiHBQAJ3teZ2p5xAC:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L239)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

NotImplementedError
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 247 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxuwJpE_WBOArdJR_i:-NhVWkQ59SXinTaoWMqC:b-86wd2y) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L247)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

triangulated_markers ??
</blockquote></details>

was it just a question about how I created my Q_init or was it to adapt self.Q_init = self.model.Q_from_markers(self.experimental_markers[:, :, :]) to my triangulated markers? 
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 267 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxwGJK4jVqbPo-L_vY:-NhRBtykAMYvWeTos6fV:bt39ubi) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L267)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove nb_frame
</blockquote></details>

Done.
Shouldn't I just put self.nb_frames = 1 so it is consistent with marker-based?
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 279 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngxwc9r-lvnsITL1L_e:-NhRN1Kc45DEwkPGH2Fp:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L279)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

is not None
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 414 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxzErcD-8trzQvHUkj:-NhRbkHSBKJYt2OMMvVJ:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L414)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same.
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 429 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxzQCg-MjPFjnc8wGK:-NhRX7Qs95_6uEQ_lyEc:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L429)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

NotImplementedError
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 493 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngy-aH-BnzXT6cJ0HEA:-NhVXQdb3MyNdNI-a7-e:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L493)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Get a look at:


def markers(self, Q: NaturalCoordinates) -> np.ndarray:  
    """  
    This function returns the position of the markers of the system as a function of the natural coordinates Q    also referred as forward kinematics  
    Parameters    ----------    Q : NaturalCoordinates        The natural coordinates of the segment \[12  [...]

2023-10-24 09:27 UTC, aaiaueil commented
*[`bionc/bionc_numpy/inverse_kinematics.py` line 132 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxpBMw0E8x6E-Lb2fk:-NhW-TTTC-nwOPLkMGY7:b-69ppim) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L132)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

or should I code it myself directly in biomechanical_model class?
</blockquote></details>

update : did it but can't figure out how to get the values (:


<!-- Sent from Reviewable.io -->

2023-10-24 16:17 UTC, Ipuch requested changes
> Reviewed 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98)* status: all files reviewed, 24 unresolved discussions (waiting on @aaiaueil)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 188 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngxrn7R7zaODvSMMEld:-NhXM7Lm2kXzC-XuIJ94:b-g7gb3s) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L188)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

shouldn't I leave str = None ? I get an error saying "non-default argument follows default argument" when I remove str = None
</blockquote></details>

     experimental_markers: np.ndarray  = None,
     experimental_heatmaps: dict[str, np.ndarray]  = None,
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 429 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxzQCg-MjPFjnc8wGK:-NhXRr665HKgkMyEIGzb:b-x0r7bi) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L429)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

NotImplementedError("Not possible to do all frames at the same time for the heatmaps")
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 95 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXKEDJCuYzSoV9ebWO:-NhXKEDJCuYzSoV9ebWP:b-j43py3) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L95)):*
> ```Python
>     ----------
>     model_keypoints : MX
>         The position of the 3D point in global reference frame
> ```

[3 x 1], symbolic expression, also known model_markers, also known as keypoints on openpose for example.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 99 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXKbL62BuRhTjjK3BC:-NhXKbL7DY0luEMSXn7R:b-pnuolj) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L99)):*
> ```Python
>         The 3x4 calibration matrix of the considered camera
>     gaussian_magnitude : MX
>         Amplitude of the gaussian considered
> ```

[1 x 1]
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 101 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXKiMy4ztRvKTrNovi:-NhXKiMy4ztRvKTrNovj:b-ry1z0n) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L101)):*
> ```Python
>         Amplitude of the gaussian considered
>     gaussian_center : MX
>         Position of the center of the gaussian considered
> ```

[2 x 1], along x and y
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 103 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXKmjs1Pwu9tD5aAf2:-NhXKmjs1Pwu9tD5aAf3:b8dx6d9) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L103)):*
> ```Python
>         Position of the center of the gaussian considered
>     gaussian_standard_deviation : MX
>         Standard deviation of the gaussian considered
> ```

[2 x 1] along x and y
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 110 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXL6kXEgtckj5mGlWO:-NhXL6kXEgtckj5mGlWP:bon5ylo) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L110)):*
> ```Python
>                 (
>                     (
>                         (dot(model_keypoints, camera_calibration_matrix[1, 0:3].T) + camera_calibration_matrix[1, 3])
> ```

Try to write a line 
projected_markers_in_global = ....
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 144 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXL_lA9idIAe0yU7VE:-NhXL_lA9idIAe0yU7VF:b-zcwl15) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L144)):*
> ```Python
>     experimental_markers : np.ndarray | str
>         The experimental markers (3xNxM numpy array), or a path to a c3d file
>     experimental_heatmaps : dict[str, np.ndarray] ==> to be modified
> ```

remove : "=> to be modified"
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 145 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXQxtq25FiWZFzUVQp:-NhXQxtq25FiWZFzUVQq:b2k6yuq) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L145)):*
> ```Python
>         The experimental markers (3xNxM numpy array), or a path to a c3d file
>     experimental_heatmaps : dict[str, np.ndarray] ==> to be modified
>         The experimental heatmaps, composed of two arrays and one float : camera_parameters (3 x 4 x nb_cameras numpy array), gaussian_parameters (5 x M x N x nb_cameras numpy array)
> ```

Changer la documentation, nb_camera standard as the terminal dimension
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 198 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXMIFlDusWGNi3-Aaw:-NhXMIFlDusWGNi3-Aax:bf3g51c) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L198)):*
> ```Python
>         model : BiomechanicalModel
>             The model considered (bionc.numpy)
>         experimental_markers : np.ndarray | str
> ```

remove "| str"
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 200 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXMG4l-pcjiRe_Zs1F:-NhXMG4l-pcjiRe_Zs1G:bodbx2o) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L200)):*
> ```Python
>         experimental_markers : np.ndarray | str
>             The experimental markers (3xNxM numpy array), or a path to a c3d file
>         experimental_heatmaps : dict[str, np.ndarray] ==> to be modified
> ```

"to be modfied" to remove too
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 227 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXMpNP8Qu7PkrJraUI:-NhXMpNP8Qu7PkrJraUJ:b-yqgz9i) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L227)):*
> ```Python
>             raise ValueError("Q_init must be provided for heatmap analysis")
>         else:
>             self.Q_init = Q_init
> ```

```python3
if Q_init is None:
            if experimental_heatmaps is not None:
                NotImplementedError("Not available yet, please provide a Q_init")
            self.Q_init = self.model.Q_from_markers(self.experimental_markers[:, :, :])
        else:
            self.Q_init = Q_init
```



_Code quote:_
```Python
        if Q_init is None and self.experimental_markers is not None:
            self.Q_init = self.model.Q_from_markers(self.experimental_markers[:, :, :])
        elif Q_init is None and self.experimental_heatmaps is not None:
            raise ValueError("Q_init must be provided for heatmap analysis")
        else:
            self.Q_init = Q_init
```
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 261 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXOQGt45FNfkBCIRXK:-NhXOQGt45FNfkBCIRXL:b-o2g5km) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L261)):*
> ```Python
> 
>         if experimental_heatmaps is not None:
>             if isinstance(experimental_heatmaps, dict):
> ```

if not isinstance(experimental_heatmaps, dict):
    raise ....

if not experimental_heatmaps["gaussian_parameters].shape[1] == 5:
    raise ....

if not len(experimental_heatmaps["camera_parameters].shape[2])== 4:
    raise  ....

if not experimental_heatmaps["camera_parameters].shape[1] == 3:
    raise ....

 [...]

2023-10-24 18:46 UTC, Ipuch requested changes
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98)* status: all files reviewed, 25 unresolved discussions (waiting on @aaiaueil)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 508 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhY-9uE4IHlqDCMBLAV:-NhY-9uE4IHlqDCMBLAW:b-m3tahc) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L508)):*
> ```Python
>         Q_f = NaturalCoordinates(Q)
>         for m in range(self.model.nb_markers):
>             X = self._model_mx.markers(Q_f)[:, m]
> ```

Do it out of the loop:
marker_positions = self._model_mx.markers(Q_f)
for m in range(self.model.nb_markers):
     ....
     error_m += _compute_confidence_value_for_one_heatmap(marker_positions[:,m], cal, amp, pos, sig)


<!-- Sent from Reviewable.io -->

2023-10-31 08:48 UTC, aaiaueil reviewed
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98)* status: 3 of 4 files reviewed, 25 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 188 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ngxrn7R7zaODvSMMEld:-Ni-mliu0xAwPS-GvDf6:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L188)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

experimental_markers: np.ndarray  = None,
     experimental_heatmaps: dict[str, np.ndarray]  = None,
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 429 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxzQCg-MjPFjnc8wGK:-Ni03jBmAdGubdZXbX7_:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L429)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

NotImplementedError("Not possible to do all frames at the same time for the heatmaps")
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 95 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXKEDJCuYzSoV9ebWO:-Ni-fdi9CNlcIc-mCeuf:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L95)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

[3 x 1], symbolic expression, also known model_markers, also known as keypoints on openpose for example.
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 99 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXKbL62BuRhTjjK3BC:-Ni-gAcV1NFpLl8N_L1x:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L99)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

[1 x 1]
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 101 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXKiMy4ztRvKTrNovi:-Ni-gTXG3c3Rguwxf2i1:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L101)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

[2 x 1], along x and y
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 103 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXKmjs1Pwu9tD5aAf2:-Ni-gZUP2154p9oBXd7x:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L103)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

[2 x 1] along x and y
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 110 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXL6kXEgtckj5mGlWO:-Ni-jexXAgVvrolqjrv8:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L110)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Try to write a line 
projected_markers_in_global = ....
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 144 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXL_lA9idIAe0yU7VE:-Ni-kNku2JO9AcCFUCUJ:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L144)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove : "=> to be modified"
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 145 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXQxtq25FiWZFzUVQp:-Ni-mBlv5x061FJwWT_G:beaadfn) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L145)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Changer la documentation, nb_camera standard as the terminal dimension
</blockquote></details>

Done. Now it is the first dimension
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 198 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXMIFlDusWGNi3-Aaw:-Ni-n5eB77dNRDIGR2qo:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L198)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove "| str"
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 200 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXMG4l-pcjiRe_Zs1F:-Ni-nAJ77lz1vt8OdEOl:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L200)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"to be modfied" to remove too
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 227 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXMpNP8Qu7PkrJraUI:-Ni-odyhC_x804_FfN0x:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L227)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

```python3
if Q_init is None:
            if experimental_heatmaps is not None:
                NotImplementedError("Not available yet, please provide a Q_init")
            self.Q_init = self.model.Q_from_markers(self.experimental_markers[:, :, :])
        else:
            self.Q_init = Q_init
```
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 261 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXOQGt45FNfkBCIRXK:-Ni-x64A4MGMBbqW8gVK:b-wph3iv) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L261)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

if not isinstance(experimental_heatmaps, dict):
    raise ....

if not experimental_heatmaps["gaussian_parameters].shape[1] == 5:
    raise ....

if not len(experimental_heatmaps["camera_parameters].shape[2])== 4:
    raise  ....

if not experimental_heatmaps["camera_parameters].shape[1] == 3:
    raise ....

if not experimental_heatmaps["camera_parameters].shape[2] == 4:
    raise ....

if not len(experimental_heatmaps["camera_parameters].shape) == 3:
    raise ....

if not experimental_heatmaps["camera_parameters].shape[0] ==  experimental_heatmaps["camera_parameters].shape[0]
 raise ...

if more do it :)
</blockquote></details>

Done. Did not see other tests to run
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 288 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXPTfQ7gEKg4y8j567:-Ni-xqhA8s4C1QqFD23h:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L288)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This else should disappear
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 299 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXRRFdDByjWOqa6nD0:-Ni02KXH6abvZOHUYfBB:bk672h5) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L299)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

no If in this function.
You need a empty MX M [...]

2023-10-31 19:50 UTC, Ipuch requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98)* status: all files reviewed, 11 unresolved discussions (waiting on @aaiaueil)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 429 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxzQCg-MjPFjnc8wGK:-Ni6Gnp683jt0A2IXbEp:b-imc2mx) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L429)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Try to enhance my error message each time :)
NotImplementedError("Not possible to solve for all frames with experimental_heatmaps")
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 508 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXSSMMCuDDtwqt7fvF:-Ni6GwoP6XdqI4K3z-tk:blwvtje) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L508)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

Did not implement it : doesn't work. See error attached
</blockquote></details>

We need to talk about it
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 111 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6DLNLCjB0oaiesYc0:-Ni6DLNLCjB0oaiesYc1:b2ni4ez) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L111)):*
> ```Python
>     marker_projected_on_y = (
>         dot(model_markers, camera_calibration_matrix[0, 0:3].T) + camera_calibration_matrix[0, 3]
>     ) / (dot(model_markers, camera_calibration_matrix[2, 0:3].T) + camera_calibration_matrix[2, 3])
> ```

hum
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 255 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6EGOmDsKd-GHCiR6y:-Ni6EGOmDsKd-GHCiR6z:b-4erxii) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L255)):*
> ```Python
> 
>             if not len(experimental_heatmaps["camera_parameters"].shape) == 3:
>                 raise ValueError("Length of camera parameters must be 3")
> ```

Be more precise on error message, try to be at the place of someone who has not coded this part him/herself.

"The number of dimension of the NumPy array stored in of experimental_heatmaps["camera_parameters"] must be 3, and the expected shape is nb_cameras x 3 x 4."
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 270 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6EtnFAF6JqDoVqEMc:-Ni6EtnFAF6JqDoVqEMd:bvq4nc) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L270)):*
> ```Python
>                 == experimental_heatmaps["gaussian_parameters"].shape[0]
>             ):
>                 raise ValueError("First dimension should be equal for camera parameters and gaussian parameters")
> ```

f"First dimension of experimental_heatmaps["camera_parameters"] and experimental_heatmaps["gaussian_parameters"] should be equal currently we have {experimental_heatmaps["camera_parameters"].shape[0]} and {experimental_heatmaps["gaussian_parameters"].shape[0]}."


<!-- Sent from Reviewable.io -->

2023-10-31 20:10 UTC, Ipuch requested changes
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98)* status: all files reviewed, 11 unresolved discussions (waiting on @aaiaueil)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 145 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXQxtq25FiWZFzUVQp:-Ni6LCcA-gn_69XN7zvz:b6z35xo) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L145)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

Done. Now it is the first dimension
</blockquote></details>

I really doesn't like the nb_camera first, because it's not standard ... 
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 508 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXSSMMCuDDtwqt7fvF:-Ni6KfHm0pQOQB613pjp:b-k8iven) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L508)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

We need to talk about it
</blockquote></details>

This is why your IK is not working yet.

This either need to be implemented properly, or to find a temporary hack
such as technical_marker_names =model.marker_names_technical()
find index in model.marker_names()
technical_markers = model.markers(Q)[index]
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 426 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6JnYhDjDaGIMLEJ00:-Ni6JnYhDjDaGIMLEJ01:bkqipua) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L426)):*
> ```Python
>                 objective = self._objective_function(
>                     self._Q_sym, experimental_marker_frame, self.camera_parameters, gaussian_parameters_frame
>                 )
> ```

Maybe like this:

"
objective = self._objective_function(
                    self._Q_sym, 
                    [] if self.experimental_markers is None else self.experimental_markers[:, :, f], 
                    [] if self.experimental_heatmaps is None else self.camera_parameters, 
                    [] if self.experimental_heatmaps is None else self.gaussian_parameters[:, :, f], 
                )



_Code quote:_
```Python
                objective = self._objective_function(
                    self._Q_sym, experimental_marker_frame, self.camera_parameters, gaussian_parameters_frame
                )
```
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 513 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6LdtGCBOwkvRtYTLL:-Ni6LdtH4DCYFJzrSc4N:baex125) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L513)):*
> ```Python
>                 gaussian_magnitude = gaussian[4, m]
>                 gaussian_center = gaussian[0:2, m]
>                 gaussian_standard_deviation = gaussian[2:4, m]
> ```

This should be documented in the docstring at the top of the class,


<!-- Sent from Reviewable.io -->

2023-11-07 09:22 UTC, aaiaueil reviewed
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98)* status: all files reviewed, 11 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 429 at r3](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgxzQCg-MjPFjnc8wGK:-Nid2F_iD8r46-3YUDMh:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/5ab7974e424e398967689a2d37d5f2e9b5ec6ae5/bionc/bionc_numpy/inverse_kinematics.py#L429)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Try to enhance my error message each time :)
NotImplementedError("Not possible to solve for all frames with experimental_heatmaps")
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 508 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXSSMMCuDDtwqt7fvF:-Nid3Wv8Ae3zTAriyWU0:buso8w0) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/inverse_kinematics.py#L508)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This is why your IK is not working yet.

This either need to be implemented properly, or to find a temporary hack
such as technical_marker_names =model.marker_names_technical()
find index in model.marker_names()
technical_markers = model.markers(Q)[index]
</blockquote></details>

okay let's discuss
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 111 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6DLNLCjB0oaiesYc0:-Nicu6hQ-eCG_OYQYSIz:b-ogrtl) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L111)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

hum
</blockquote></details>

Which part do you dislike (more)?
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 255 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6EGOmDsKd-GHCiR6y:-NicvM_wCunUSXfFTdIq:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L255)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Be more precise on error message, try to be at the place of someone who has not coded this part him/herself.

"The number of dimension of the NumPy array stored in of experimental_heatmaps["camera_parameters"] must be 3, and the expected shape is nb_cameras x 3 x 4."
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 270 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6EtnFAF6JqDoVqEMc:-NicwzGb2ovlDRGx09Ur:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L270)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

f"First dimension of experimental_heatmaps["camera_parameters"] and experimental_heatmaps["gaussian_parameters"] should be equal currently we have {experimental_heatmaps["camera_parameters"].shape[0]} and {experimental_heatmaps["gaussian_parameters"].shape[0]}."
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 426 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6JnYhDjDaGIMLEJ00:-Nid1VIj9YL-bWCmV0yx:bryk26a) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L426)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Maybe like this:

"
objective = self._objective_function(
                    self._Q_sym, 
                    [] if self.experimental_markers is None else self.experimental_markers[:, :, f], 
                    [] if self.experimental_heatmaps is None else self.camera_parameters, 
                    [] if self.experimental_heatmaps is None else self.gaussian_parameters[:, :, f], 
                )
</blockquote></details>

Looks good (and fancier)
___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 513 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6LdtGCBOwkvRtYTLL:-Nid4N406ZBEWaMbOf65:b-elcj6z) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L513)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This should be documented in the docstring at the top of the class,
</blockquote></details>

see line 131


<!-- Sent from Reviewable.io -->

2023-11-07 09:43 UTC, aaiaueil reviewed
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98)* status: 3 of 4 files reviewed, 11 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_numpy/natural_segment.py` line 151 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVlkE3CPWqYgpJAmr3:-Nid768T7WTILybyxvl3:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L151)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/natural_segment.py` line 282 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVlmLo0EUBhBBXghle:-Nid7PgH5obZ3DcnXJFY:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L282)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/natural_segment.py` line 288 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVloCLDyvckQevTwnS:-Nid7Z-Z8qcNNQrpPVnQ:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L288)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/natural_segment.py` line 311 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVlpopBcsgNb6S4UIn:-Nid7cOn8hXYERbZCwDv:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L311)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/natural_segment.py` line 342 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVlqjG02eVrk0HK4K9:-Nid80tgDtBsgkad8__D:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L342)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/natural_segment.py` line 424 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVlrRE4G0vL7A0yfrg:-Nid86YRAetDz4zy9ore:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L424)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/natural_segment.py` line 593 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVlsAR0oPJE-ZLiRv6:-Nid8EC10LCPPXsy0sxk:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L593)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/natural_segment.py` line 641 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVlt-M706o9byI8TEF:-Nid8OOKBPP4Xh0TNGJg:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L641)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/natural_segment.py` line 786 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVltqW8COi0NMiFI-L:-Nid8Xh_33mdOR1dWOVd:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L786)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/natural_segment.py` line 809 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVluZs5gBrWbo1pYJh:-Nid8e7d2SWQ5hCfGrPi:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L809)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/natural_segment.py` line 899 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVlxKA3IiKkZ0UdglF:-Nid92qo4-FcHz8Od58j:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L899)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done
___
*[`bionc/bionc_numpy/natural_segment.py` line 916 at r1](https://reviewable.io/reviews/Ipuch/bioNC/98#-NgVly3b2SQzMTaNnTNn:-Nid9Kc_1oyC1Lj9vOz0:b-brsxau) ([raw file](https://github.com/Ipuch/bioNC/blob/e320465f8f9224964b34cd639b14c65cc7dce554/bionc/bionc_numpy/natural_segment.py#L916)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

unblack
</blockquote></details>

Done

Did not push though as I wasn't sure it was on the correct branch
___
*[`bionc/bionc_numpy/biomechanical_model.py` line 1026 at r5](https://reviewable.io/reviews/Ipuch/bioNC/98#-NhXIVZgAdhfHPJNoYaq:-Nid9TIa24h_AiRuAESD:b3kre) ([raw file](https://github.com/Ipuch/bioNC/blob/14e8b922207f3797f5645452aab7fa1eb68871a2/bionc/bionc_numpy/biomechanical_model.py#L1026)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

To be removed !
</blockquote></details>

?


<!-- Sent from Reviewable.io -->

2023-11-07 17:24 UTC, Ipuch requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @aaiaueil)

___
*[`bionc/bionc_numpy/inverse_kinematics.py` line 111 at r8](https://reviewable.io/reviews/Ipuch/bioNC/98#-Ni6DLNLCjB0oaiesYc0:-NieZe4v5Y75331jvE7G:b5sn5a9) ([raw file](https://github.com/Ipuch/bioNC/blob/6927620e38c6e2fd976f704ffcce2a2a310c2279/bionc/bionc_numpy/inverse_kinematics.py#L111)):*
<details><summary><i>Previously, aaiaueil wrote…</i></summary><blockquote>

Which part do you dislike (more)?
</blockquote></details>

- new function def project_markers_on_XXX_from_XXX(vecteur(?)=, axis=)"
- displace files heatmap_helpers.py


<!-- Sent from Reviewable.io -->

2023-11-20 17:22 UTC, Ipuch commented
I want to close that pull request, it has been a while now.
Expected work before next meeting:

- Tests need to be pushed and works
- nb_camera as the last dimension of vectors entry
- merge main into your branch and resolves the conflicts.
- tests should still pass code should be linted

2023-11-28 16:14 UTC, Ipuch approved these changes
> Reviewed 1 of 4 files at r14, 2 of 3 files at r16, 7 of 7 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaiaueil)



<!-- Sent from Reviewable.io -->

2023-11-28 16:14 UTC, Ipuch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/98#-:-NkLhVMQ-mcRORf3Ppl2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaiaueil)



<!-- Sent from Reviewable.io -->

2023-11-28 16:20 UTC, merged